// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sumit Patel

/**
 * `prismalens init` — scaffold a prismalens.config.yaml in the cwd.
 *
 * Behaviour (intentionally non-interactive, unlike the retired pl orchestrator's
 * wizard): if a prismalens.config.yaml already exists, print a notice and do
 * nothing; otherwise write a commented default. Values are sourced from the Zod
 * schema's defaults so the scaffold can't drift from what the engine actually uses.
 */
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { INVESTIGATION_DEFAULTS } from "@prismalens/config/investigation";
import { defineCommand } from "citty";
import consola from "consola";
import {
	AgentConfigSchema,
	type PlConfig,
	PlConfigSchema,
} from "../config/schema.js";

const CONFIG_FILENAME = "prismalens.config.yaml";

/** Render a commented default config, sourcing live values from schema defaults. */
function renderDefaultConfig(d: PlConfig): string {
	const harnessOptions = AgentConfigSchema.shape.default
		.removeDefault()
		.options.join(" | ");
	return `# prismalens.config.yaml — investigation engine configuration (ADR-0008/0010).
# Generated by \`prismalens init\`. Unset values fall back to built-in defaults;
# \`prismalens doctor\` checks the bits that gate a run.

# Repository under investigation (owner/name). Auto-detected from the git remote
# when omitted.
# repo: owner/name

# Tier-2 harness backend the supervisor rents (ADR-0008).
agent:
  # Which agent harness to rent: ${harnessOptions}
  default: ${d.agent.default}
  # BARE model id, e.g. "gpt-oss:120b" — the harness applies its own provider prefix.
  # Omit to let the chosen harness pick its own default.
  # model: gpt-oss:120b

# Read-only telemetry + app endpoints the harness may query. Point these at your
# stack; defaults assume a local dev setup.
telemetry:
  prometheusUrl: ${INVESTIGATION_DEFAULTS.telemetry.prometheusUrl}
  alertmanagerUrl: ${INVESTIGATION_DEFAULTS.telemetry.alertmanagerUrl}
  apiUrl: ${INVESTIGATION_DEFAULTS.telemetry.apiUrl}

# Read-only log-query system the harness may curl (Loki, Elasticsearch, …).
# logs:
#   kind: loki
#   url: http://localhost:3100

# Service catalog (ADR-0015). The alert's \`service\` label (else \`namespace\`/\`job\`)
# selects an entry; \`--service <name>\` overrides. The matched service's repo/tier/
# deps ride into the investigation context so a single-alert run isn't context-free.
# services:
#   checkout:
#     tier: tier-1
#     repo: acme/checkout
#     depends_on: [payments, inventory]

# Where runs, events, and reports are stored.
workspace:
  base_dir: ${d.workspace.base_dir}

# \`pl listen\` — token-authed local webhook intake (Alertmanager). The token is
# REQUIRED to start listening; keep it out of the file via env interpolation.
# listen:
#   port: ${d.listen.port}
#   token: "\${PRISMALENS_LISTEN_TOKEN}"
#   max_pending: ${d.listen.max_pending}
`;
}

export default defineCommand({
	meta: {
		name: "init",
		description: `Scaffold a ${CONFIG_FILENAME} in the current directory`,
	},
	async run({ args, cmd }) {
		try {
			for (const key of Object.keys(args)) {
				if (key !== "_" && !(cmd?.args as Record<string, unknown>)?.[key]) {
					consola.error(`Unknown option: --${key}`);
					process.exit(1);
				}
			}
			const configPath = resolve(process.cwd(), CONFIG_FILENAME);
			if (existsSync(configPath)) {
				consola.info(
					`${CONFIG_FILENAME} already exists at ${configPath} — leaving it untouched.`,
				);
				return;
			}

			// PlConfigSchema.parse({}) yields the fully-defaulted config; the scaffold
			// renders those exact values so it never drifts from the schema.
			const defaults = PlConfigSchema.parse({});
			await writeFile(configPath, renderDefaultConfig(defaults), "utf-8");

			consola.success(`Created ${configPath}`);
			consola.info(
				"Edit it for your stack, then run `prismalens doctor` to verify your environment.",
			);
		} catch (err) {
			consola.error(err instanceof Error ? err.message : String(err));
			process.exit(1);
		}
	},
});
