/**
 * `prismalens init` — scaffold a prismalens.config.yaml in the cwd.
 *
 * Behaviour (intentionally non-interactive, unlike the retired pl orchestrator's
 * wizard): if a prismalens.config.yaml already exists, print a notice and do
 * nothing; otherwise write a commented default. Values are sourced from the Zod
 * schema's defaults so the scaffold can't drift from what the engine actually uses.
 */
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { defineCommand } from "citty";
import consola from "consola";
import { type PlConfig, PlConfigSchema } from "../config/schema.js";

const CONFIG_FILENAME = "prismalens.config.yaml";

/** Render a commented default config, sourcing live values from schema defaults. */
function renderDefaultConfig(d: PlConfig): string {
	const allowList = d.agent.shell_allow_list.join(", ");
	return `# prismalens.config.yaml — investigation engine configuration (ADR-0008/0010).
# Generated by \`prismalens init\`. Unset values fall back to built-in defaults;
# \`prismalens doctor\` checks the bits that gate a run.

# Repository under investigation (owner/name). Auto-detected from the git remote
# when omitted.
# repo: owner/name

# Tier-2 harness backend the supervisor rents (ADR-0008).
agent:
  # Which agent harness to rent: deepagents | claude-code | codex
  default: ${d.agent.default}
  # Provider-prefixed model id, e.g. "openai:gpt-oss:120b".
  # Omit to let the chosen harness pick its own default.
  # model: openai:gpt-oss:120b
  # Per-run wall-clock budget for the harness (ms).
  timeout_ms: ${d.agent.timeout_ms}
  # Shell commands auto-approved for the harness (read-only by intent).
  shell_allow_list: [${allowList}]

# Read-only telemetry + app endpoints the harness may query. Point these at your
# stack; defaults assume a local dev setup.
telemetry:
  prometheusUrl: http://localhost:9090
  alertmanagerUrl: http://localhost:9093
  apiUrl: http://localhost:5000

# Where runs, events, and reports are stored.
workspace:
  base_dir: ${d.workspace.base_dir}

# Engine runtime: process (in-process M2 engine) | tmux (legacy opt-in).
plugins:
  runtime: ${d.plugins.runtime}

# Logging.
logging:
  level: ${d.logging.level}
  format: ${d.logging.format}
`;
}

export default defineCommand({
	meta: {
		name: "init",
		description: `Scaffold a ${CONFIG_FILENAME} in the current directory`,
	},
	async run() {
		const configPath = resolve(process.cwd(), CONFIG_FILENAME);

		if (existsSync(configPath)) {
			consola.info(
				`${CONFIG_FILENAME} already exists at ${configPath} — leaving it untouched.`,
			);
			return;
		}

		// PlConfigSchema.parse({}) yields the fully-defaulted config; the scaffold
		// renders those exact values so it never drifts from the schema.
		const defaults = PlConfigSchema.parse({});
		await writeFile(configPath, renderDefaultConfig(defaults), "utf-8");

		consola.success(`Created ${configPath}`);
		consola.info(
			"Edit it for your stack, then run `prismalens doctor` to verify your environment.",
		);
	},
});
