/**
 * `prismalens init` — scaffold a prismalens.config.yaml in the cwd.
 *
 * Behaviour (intentionally non-interactive, unlike the retired pl orchestrator's
 * wizard): if a prismalens.config.yaml already exists, print a notice and do
 * nothing; otherwise write a commented default. Values are sourced from the Zod
 * schema's defaults so the scaffold can't drift from what the engine actually uses.
 */
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { INVESTIGATION_DEFAULTS } from "@prismalens/config/investigation";
import { defineCommand } from "citty";
import consola from "consola";
import {
	AgentConfigSchema,
	type PlConfig,
	PlConfigSchema,
} from "../config/schema.js";

const CONFIG_FILENAME = "prismalens.config.yaml";

/** Render a commented default config, sourcing live values from schema defaults. */
function renderDefaultConfig(d: PlConfig): string {
	const allowList = d.agent.shell_allow_list.join(", ");
	const harnessOptions = AgentConfigSchema.shape.default
		.removeDefault()
		.options.join(" | ");
	return `# prismalens.config.yaml — investigation engine configuration (ADR-0008/0010).
# Generated by \`prismalens init\`. Unset values fall back to built-in defaults;
# \`prismalens doctor\` checks the bits that gate a run.

# Repository under investigation (owner/name). Auto-detected from the git remote
# when omitted.
# repo: owner/name

# Tier-2 harness backend the supervisor rents (ADR-0008).
agent:
  # Which agent harness to rent: ${harnessOptions}
  default: ${d.agent.default}
  # Provider-prefixed model id, e.g. "openai:gpt-oss:120b".
  # Omit to let the chosen harness pick its own default.
  # model: openai:gpt-oss:120b
  # Per-run wall-clock budget for the harness (ms).
  timeout_ms: ${d.agent.timeout_ms}
  # Shell commands auto-approved for the harness (read-only by intent).
  shell_allow_list: [${allowList}]

# Read-only telemetry + app endpoints the harness may query. Point these at your
# stack; defaults assume a local dev setup.
telemetry:
  prometheusUrl: ${INVESTIGATION_DEFAULTS.telemetry.prometheusUrl}
  alertmanagerUrl: ${INVESTIGATION_DEFAULTS.telemetry.alertmanagerUrl}
  apiUrl: ${INVESTIGATION_DEFAULTS.telemetry.apiUrl}

# Read-only log-query system the harness may curl (Loki, Elasticsearch, …). Distinct
# from \`logging\` below (the CLI's own log-output level/format).
# logs:
#   kind: loki
#   url: http://localhost:3100

# Service catalog (ADR-0015). The alert's \`service\` label (else \`namespace\`/\`job\`)
# selects an entry; \`--service <name>\` overrides. The matched service's repo/tier/
# deps ride into the investigation context so a single-alert run isn't context-free.
# services:
#   checkout:
#     tier: tier-1
#     repo: acme/checkout
#     depends_on: [payments, inventory]

# Where runs, events, and reports are stored.
workspace:
  base_dir: ${d.workspace.base_dir}

# Logging.
logging:
  level: ${d.logging.level}
  format: ${d.logging.format}
`;
}

export default defineCommand({
	meta: {
		name: "init",
		description: `Scaffold a ${CONFIG_FILENAME} in the current directory`,
	},
	async run() {
		const configPath = resolve(process.cwd(), CONFIG_FILENAME);

		if (existsSync(configPath)) {
			consola.info(
				`${CONFIG_FILENAME} already exists at ${configPath} — leaving it untouched.`,
			);
			return;
		}

		// PlConfigSchema.parse({}) yields the fully-defaulted config; the scaffold
		// renders those exact values so it never drifts from the schema.
		const defaults = PlConfigSchema.parse({});
		await writeFile(configPath, renderDefaultConfig(defaults), "utf-8");

		consola.success(`Created ${configPath}`);
		consola.info(
			"Edit it for your stack, then run `prismalens doctor` to verify your environment.",
		);
	},
});
