import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { EnvironmentVariables } from '@prismalens/config';
import { TokenVault } from '@prismalens/integrations';

/**
 * NestJS wrapper around TokenVault for credential encryption.
 */
@Injectable()
export class CredentialsService implements OnModuleInit {
  private readonly logger = new Logger(CredentialsService.name);
  private vault!: TokenVault;

  constructor(private configService: ConfigService<EnvironmentVariables>) {}

  onModuleInit(): void {
    const keyHex = this.configService.get('PRISMALENS_ENCRYPTION_KEY');

    if (!keyHex) {
      throw new Error(
        'PRISMALENS_ENCRYPTION_KEY not available. ' +
          'The key is auto-generated by @prismalens/config if not provided.',
      );
    }

    this.vault = TokenVault.fromHex(keyHex);
    this.logger.log('TokenVault initialized successfully');
  }

  getVault(): TokenVault {
    return this.vault;
  }

  encrypt<T>(data: T): Uint8Array<ArrayBuffer> {
    return new Uint8Array(
      this.vault.encryptJSON(data),
    ) as Uint8Array<ArrayBuffer>;
  }

  encryptToBase64<T>(data: T): string {
    return Buffer.from(this.vault.encryptJSON(data)).toString('base64');
  }

  decryptFromBase64<T>(base64: string): T {
    return this.vault.decryptJSON<T>(Buffer.from(base64, 'base64'));
  }

  decrypt<T>(data: Uint8Array | Buffer): T {
    return this.vault.decryptJSON<T>(Buffer.from(data));
  }

  mask(credentials: Record<string, unknown>): Record<string, unknown> {
    return TokenVault.mask(credentials);
  }
}
