/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations/index'
import { Route as ServicesIdIndexRouteImport } from './routes/services/$id/index'
import { Route as InvestigationsIdIndexRouteImport } from './routes/investigations/$id/index'
import { Route as IncidentsIdIndexRouteImport } from './routes/incidents/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdIndexRoute = ServicesIdIndexRouteImport.update({
  id: '/services/$id/',
  path: '/services/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIdIndexRoute = InvestigationsIdIndexRouteImport.update({
  id: '/investigations/$id/',
  path: '/investigations/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdIndexRoute = IncidentsIdIndexRouteImport.update({
  id: '/incidents/$id/',
  path: '/incidents/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/setup': typeof SetupIndexRoute
  '/incidents/$id': typeof IncidentsIdIndexRoute
  '/investigations/$id': typeof InvestigationsIdIndexRoute
  '/services/$id': typeof ServicesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/setup': typeof SetupIndexRoute
  '/incidents/$id': typeof IncidentsIdIndexRoute
  '/investigations/$id': typeof InvestigationsIdIndexRoute
  '/services/$id': typeof ServicesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/incidents/$id/': typeof IncidentsIdIndexRoute
  '/investigations/$id/': typeof InvestigationsIdIndexRoute
  '/services/$id/': typeof ServicesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/investigations'
    | '/services'
    | '/settings'
    | '/setup'
    | '/incidents/$id'
    | '/investigations/$id'
    | '/services/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/investigations'
    | '/services'
    | '/settings'
    | '/setup'
    | '/incidents/$id'
    | '/investigations/$id'
    | '/services/$id'
  id:
    | '__root__'
    | '/'
    | '/investigations/'
    | '/services/'
    | '/settings/'
    | '/setup/'
    | '/incidents/$id/'
    | '/investigations/$id/'
    | '/services/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  IncidentsIdIndexRoute: typeof IncidentsIdIndexRoute
  InvestigationsIdIndexRoute: typeof InvestigationsIdIndexRoute
  ServicesIdIndexRoute: typeof ServicesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id/': {
      id: '/services/$id/'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$id/': {
      id: '/investigations/$id/'
      path: '/investigations/$id'
      fullPath: '/investigations/$id'
      preLoaderRoute: typeof InvestigationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id/': {
      id: '/incidents/$id/'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  IncidentsIdIndexRoute: IncidentsIdIndexRoute,
  InvestigationsIdIndexRoute: InvestigationsIdIndexRoute,
  ServicesIdIndexRoute: ServicesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
