/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedInvestigationsIndexRouteImport } from './routes/_authenticated/investigations/index'
import { Route as AuthenticatedIncidentsIndexRouteImport } from './routes/_authenticated/incidents/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedServicesIdIndexRouteImport } from './routes/_authenticated/services/$id/index'
import { Route as AuthenticatedInvestigationsIdIndexRouteImport } from './routes/_authenticated/investigations/$id/index'
import { Route as AuthenticatedIncidentsIdIndexRouteImport } from './routes/_authenticated/incidents/$id/index'
import { Route as AuthenticatedSettingsIntegrationsConfigureRouteImport } from './routes/_authenticated/settings/integrations/configure'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestigationsIndexRoute =
  AuthenticatedInvestigationsIndexRouteImport.update({
    id: '/investigations/',
    path: '/investigations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncidentsIndexRoute =
  AuthenticatedIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesIdIndexRoute =
  AuthenticatedServicesIdIndexRouteImport.update({
    id: '/services/$id/',
    path: '/services/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestigationsIdIndexRoute =
  AuthenticatedInvestigationsIdIndexRouteImport.update({
    id: '/investigations/$id/',
    path: '/investigations/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncidentsIdIndexRoute =
  AuthenticatedIncidentsIdIndexRouteImport.update({
    id: '/incidents/$id/',
    path: '/incidents/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIntegrationsConfigureRoute =
  AuthenticatedSettingsIntegrationsConfigureRouteImport.update({
    id: '/settings/integrations/configure',
    path: '/settings/integrations/configure',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/setup': typeof SetupIndexRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute
  '/investigations': typeof AuthenticatedInvestigationsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/integrations/configure': typeof AuthenticatedSettingsIntegrationsConfigureRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdIndexRoute
  '/investigations/$id': typeof AuthenticatedInvestigationsIdIndexRoute
  '/services/$id': typeof AuthenticatedServicesIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/setup': typeof SetupIndexRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute
  '/investigations': typeof AuthenticatedInvestigationsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/integrations/configure': typeof AuthenticatedSettingsIntegrationsConfigureRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdIndexRoute
  '/investigations/$id': typeof AuthenticatedInvestigationsIdIndexRoute
  '/services/$id': typeof AuthenticatedServicesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/_authenticated/investigations/': typeof AuthenticatedInvestigationsIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/integrations/configure': typeof AuthenticatedSettingsIntegrationsConfigureRoute
  '/_authenticated/incidents/$id/': typeof AuthenticatedIncidentsIdIndexRoute
  '/_authenticated/investigations/$id/': typeof AuthenticatedInvestigationsIdIndexRoute
  '/_authenticated/services/$id/': typeof AuthenticatedServicesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/login'
    | '/'
    | '/setup'
    | '/alerts'
    | '/incidents'
    | '/investigations'
    | '/services'
    | '/settings'
    | '/settings/integrations/configure'
    | '/incidents/$id'
    | '/investigations/$id'
    | '/services/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/'
    | '/setup'
    | '/alerts'
    | '/incidents'
    | '/investigations'
    | '/services'
    | '/settings'
    | '/settings/integrations/configure'
    | '/incidents/$id'
    | '/investigations/$id'
    | '/services/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth/login'
    | '/_authenticated/'
    | '/setup/'
    | '/_authenticated/alerts/'
    | '/_authenticated/incidents/'
    | '/_authenticated/investigations/'
    | '/_authenticated/services/'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/integrations/configure'
    | '/_authenticated/incidents/$id/'
    | '/_authenticated/investigations/$id/'
    | '/_authenticated/services/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investigations/': {
      id: '/_authenticated/investigations/'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof AuthenticatedInvestigationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents/': {
      id: '/_authenticated/incidents/'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/$id/': {
      id: '/_authenticated/services/$id/'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AuthenticatedServicesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investigations/$id/': {
      id: '/_authenticated/investigations/$id/'
      path: '/investigations/$id'
      fullPath: '/investigations/$id'
      preLoaderRoute: typeof AuthenticatedInvestigationsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents/$id/': {
      id: '/_authenticated/incidents/$id/'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AuthenticatedIncidentsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/integrations/configure': {
      id: '/_authenticated/settings/integrations/configure'
      path: '/settings/integrations/configure'
      fullPath: '/settings/integrations/configure'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsConfigureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedIncidentsIndexRoute: typeof AuthenticatedIncidentsIndexRoute
  AuthenticatedInvestigationsIndexRoute: typeof AuthenticatedInvestigationsIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsIntegrationsConfigureRoute: typeof AuthenticatedSettingsIntegrationsConfigureRoute
  AuthenticatedIncidentsIdIndexRoute: typeof AuthenticatedIncidentsIdIndexRoute
  AuthenticatedInvestigationsIdIndexRoute: typeof AuthenticatedInvestigationsIdIndexRoute
  AuthenticatedServicesIdIndexRoute: typeof AuthenticatedServicesIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedIncidentsIndexRoute: AuthenticatedIncidentsIndexRoute,
  AuthenticatedInvestigationsIndexRoute: AuthenticatedInvestigationsIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsIntegrationsConfigureRoute:
    AuthenticatedSettingsIntegrationsConfigureRoute,
  AuthenticatedIncidentsIdIndexRoute: AuthenticatedIncidentsIdIndexRoute,
  AuthenticatedInvestigationsIdIndexRoute:
    AuthenticatedInvestigationsIdIndexRoute,
  AuthenticatedServicesIdIndexRoute: AuthenticatedServicesIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  SetupIndexRoute: SetupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
