// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sumit Patel

/**
 * Point git at the repo's checked-in hooks (`.githooks/`), so a contributor gets
 * Biome auto-fix on commit from a plain `pnpm install`.
 *
 * `core.hooksPath` rather than writing into `.git/hooks`: the hook body is then
 * version-controlled and reviewable in PRs instead of being generated by this
 * script. The trade-off is that it replaces any personal hooks for this repo —
 * if you have your own, run `git config --unset core.hooksPath` and source
 * `.githooks/pre-commit` yourself.
 *
 * This is convenience automation; CI's `Lint (Biome)` job is the enforcement.
 * Nothing here may fail an install: every failure path exits 0.
 */
import { execFileSync } from "node:child_process";

const HOOKS_PATH = ".githooks";

// CI checks out fresh, never commits, and would only pay the cost.
if (process.env.CI) process.exit(0);

/**
 * Run a git subcommand and return its trimmed stdout.
 *
 * @param {string[]} args argv for git, e.g. `["config", "--local", "core.hooksPath"]`
 * @returns {string} stdout with surrounding whitespace removed
 * @throws if git exits non-zero — every caller here treats that as "not
 *   configured" or "not a checkout" and degrades to leaving hooks unwired.
 */
function git(args) {
	return execFileSync("git", args, {
		encoding: "utf8",
		stdio: ["ignore", "pipe", "ignore"],
	}).trim();
}

try {
	// Also confirms we are inside a work tree at all.
	git(["rev-parse", "--git-common-dir"]);
} catch {
	// Not a git checkout (a tarball install, say). Nothing to wire up.
	process.exit(0);
}

try {
	if (git(["config", "--local", "--get", "core.hooksPath"]) === HOOKS_PATH) {
		process.exit(0); // already wired; keep `pnpm install` quiet
	}
} catch {
	// Unset is the normal first-run case; fall through and set it.
}

try {
	git(["config", "--local", "core.hooksPath", HOOKS_PATH]);
	console.log(`Git hooks enabled (core.hooksPath=${HOOKS_PATH}).`);
} catch {
	console.warn(
		"WARN: could not set core.hooksPath; Biome auto-fix on commit is off. CI still checks formatting.",
	);
}
