// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sumit Patel

import { defineConfig } from "tsup";

/**
 * The CLI is the ONLY published package (issue #193). The first-party
 * `@prismalens/*` closure is no longer INLINED into this bundle (issue #237):
 * `pl up` also ships the NestJS API, the forked worker and a native
 * `better-sqlite3` binding, and esbuild cannot inline a `.node` addon at all.
 * So `scripts/pack-cli.mjs` COPIES each built first-party package into the
 * published tarball's own `node_modules/@prismalens/<name>` and Node resolves
 * them the ordinary way — which is why they are `external` here.
 *
 * The third-party closure of those copied packages is hoisted into the
 * published manifest's `dependencies`, GENERATED by that same script. Never
 * hand-maintain that list: this package only works today because someone
 * hand-hoisted it once (#193), and the next divergence is an
 * `ERR_MODULE_NOT_FOUND` in a stranger's install, not a failure here.
 *
 * The command bodies in `src/cli/*` are listed as their own entries so the
 * bin's lazy `import(`../src/cli/${name}.js`)` resolves to a real emitted file
 * at `dist/src/cli/<name>.js`.
 *
 * `removeNodeProtocol: false` — tsup's default rewrites `node:sqlite` to bare
 * `sqlite`, which is NOT a valid builtin specifier (the newer builtins only
 * resolve under the `node:` prefix). That silently tripped the engine's
 * "requires Node >= 22.13" fallback at runtime.
 */
export default defineConfig({
	entry: ["bin/prismalens.ts", "src/cli/*.ts", "!src/cli/*.test.ts"],
	format: ["esm"],
	target: "node22",
	platform: "node",
	splitting: true,
	clean: true,
	dts: false,
	sourcemap: false,
	removeNodeProtocol: false,
	external: [/^@prismalens\//],
});
